### ISSUE TITLE
Lectures marked red even though they were attended

### ISSUE THREAD

**Issue by tupleu** [rcos/Venue2#142]
Before
![Screenshot_20200707-134226_Chrome](https://user-images.githubusercontent.com/57295844/87184321-cba9e680-c2b5-11ea-9114-4b30193aabdf.jpg)
After
![Screenshot_20200710-140221_Chrome](https://user-images.githubusercontent.com/57295844/87184446-0449c000-c2b6-11ea-9528-a6cb2087dc85.jpg)
![Screenshot_20200710-133516_Chrome](https://user-images.githubusercontent.com/57295844/87184482-14fa3600-c2b6-11ea-8852-c930f50096c4.jpg)

**Comment by TheStopsign** [comment]
This was a mobile-only bug, as a result from our new percentage calculations not triggering a re-rendering. Either way, it has been fixed in a branch and will be merged into production soon @tupleu. Thank you for pointing this out.
