### ISSUE TITLE
Dates out of order on Attendance History

### ISSUE THREAD

**Issue by elihschiff** [rcos/Venue2#143]
Just my opinion, but I feel like the dates under Attendance History are in the wrong order.
The months go from first to last (EX: june then july) but within the months the days go from last to first (EX: 31st, 28th, ..., 7th)

I feel like the dates should just go in order, so the months are fine but the dates should start at the smallest number in each month and count up

Here is what it currently looks like
![image](https://user-images.githubusercontent.com/18558130/87185018-095b3f00-c2b7-11ea-9502-8d91f92090a7.png)

**Comment by TheStopsign** [comment]
@elihschiff Looks like we have a wrong < or > haha, it'll be fixed in our next production build

**Comment by TheStopsign** [comment]
![image](https://user-images.githubusercontent.com/45616121/87212219-68d34200-c2eb-11ea-82e4-1baf5441aeff.png)

I believe this looks much better, wouldn't you agree, @elihschiff ?

**Comment by elihschiff** [comment]
Looks good
