### ISSUE TITLE
Progressive Web App 

### ISSUE THREAD

**Issue by nums11** [rcos/Venue2#39]
- Need to turn Venue into a PWA

**Comment by elihschiff** [comment]
I just set up a vuejs based pwa not too long ago and used this https://cli.vuejs.org/core-plugins/pwa.html

It pretty much just worked out of the box and took almost no work to set up.

The one thing I added to my website was an update button so users knew that they were on an out of date version of the website that was based off a cache. You can also do something like this that just forces a refresh if you want https://stackoverflow.com/questions/54145735/vue-pwa-not-getting-new-content-after-refresh

**Comment by nums11** [comment]
Thanks! We'll take a look.
